# application management information from Dropbox

APP_KEY = 'c8ht5mh6z6y5g82'
APP_SECRET = 'jaonmrivtj18vdd'
ACCESS_TYPE = 'dropbox'

EMAIL_ADDRESS = 'notification.secure.dropbox@gmail.com'
EMAIL_PASSWORD = 'dissertation'

FAILED_LOGIN_TOKEN = -1

SERVER_URL = 'http://127.0.0.1:8080/'
INI_FILE = 'secure_dropbox.ini'
TTE = 3600

DELETE_KEY_SUCCEED = 'DELETE KEY SUCCEED'
DELETE_KEY_FAILED = 'DELETE KEY FAILED'

UPLOAD_KEY_CHAIN_SUCCEED = 'UPLOAD KEY CHAIN SUCCEED'
UPLOAD_KEY_CHAIN_EXISTED = 'UPLOAD KEY CHAIN EXISTED'
UPLOAD_KEY_CHAIN_FAILED = 'UPLOAD KEY CHAIN FAILED'

DOWNLOAD_KEY_CHAIN_FAILED = 'DOWNLOAD KEY CHAIN FAILED'

FILE_SHARING_SUCCEED = 'FILE SHARING SUCCEED'
FILE_SHARING_EXISTED = 'FILE SHARING EXISTED'
FILE_SHARING_FAILED = 'FILE SHARING FAILED'

FILE_SHARING_CANCEL_SUCCEED = 'FILE SHARING CANCEL SUCCEED'
FILE_SHARING_CANCEL_FAILED = 'FILE SHARING CANCEL FAILED'

INVALID_USER_TIMEOUT = -2
INVALID_USER_INCORRECT_INFO = -1
INVALID_USER_NO_TOKEN = 0
VALID_USER = 1

GET_SALT_FAILED = 'GET SALT FAILED'

REGISTER_SUCCEED = 'REGISTER SUCCEED'
REGISTER_FAILED = 'REGISTER FAILED'

FETCH_PUBLIC_KEY_FAILED = 'FETCH PUBLIC KEY FAILED'

DOC_KEY_FETCH_SUCCEED = 'DOC KEY FETCH SUCCEED'
DOC_KEY_FETCH_FAILED = 'DOC KEY FETCH FAILED'

ENC = 1
DEC = 0

SHA_ITERATION = 1000
KEY_LEN = 32

BS = 16

