TTE = 3600

UPLOAD_KEY_CHAIN_SUCCEED = 'UPLOAD KEY CHAIN SUCCEED'
UPLOAD_KEY_CHAIN_FAILED = 'UPLOAD KEY CHAIN FAILED'

DOWNLOAD_KEY_CHAIN_FAILED = 'DOWNLOAD KEY CHAIN FAILED'

FILE_SHARING_SUCCEED = 'FILE SHARING SUCCEED'
FILE_SHARING_FAILED = 'FILE SHARING FAILED'

FILE_SHARING_CANCEL_SUCCEED = 'FILE SHARING CANCEL SUCCEED'
FILE_SHARING_CANCEL_FAILED = 'FILE SHARING CANCEL FAILED'

INVALID_USER_TIMEOUT = -2
INVALID_USER_INCORRECT_INFO = -1
INVALID_USER_NO_TOKEN = 0
VALID_USER = 1

GET_SALT_FAILED = 'GET SALT FAILED'

REGISTER_SUCCEED = 'REGISTER SUCCEED'
REGISTER_FAILED = 'REGISTER FAILED'

FETCH_PUBLIC_KEY_FAILED = 'FETCH PUBLIC KEY FAILED'

DOC_KEY_FETCH_SUCCEED = 'DOC KEY FETCH SUCCEED'
DOC_KEY_FETCH_FAILED = 'DOC KEY FETCH FAILED'